version: '3'

services:
  openvpn-client:
    build: .
    container_name: portmap-service
    network_mode: host
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    restart: unless-stopped
